apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{ values.name | dump }}
  annotations:
    github.com/project-slug: mythun-git/NEWTESTREPO
    # github.com/project-slug: samgabrail/${{ values.name }}
  description: ${{ values.name }}
spec:
  type: service
  owner: user:guest
  lifecycle: experimental
